package atrophy.combat.ai.conversation;

public enum Topic {
	INTIMIDATE, INTIMIDATE_REACTION, INCAP, INCAP_REACTION, JOIN, JOIN_REACTION, STEAL, GIVE_ITEMS, SHOW_ENEMIES, HELLO, NO_TRUST, ACKNOWLEDGE, YES, NO, BYE, EXIT,
	ATTACK, PAY, TRADE
}
